cc_library(
    name = "lib",
    srcs = ["error_std.c"],
    hdrs = ["dbgprintf.h"],
    deps = [
        "//lib/common:headers",
    ],
    include_prefix = ".",
    visibility = ["//visibility:public"],
)
