cc_library(
    name="lib",
    srcs=[
        "st7920.h",
        "st7920.c",
    ],
    hdrs=["st7920.h"],
    deps=[
        "//lib/lvgl:lib",
        "//spool/lib/st7920:lib",
    ],
    include_prefix = "ui",
    visibility=["//visibility:public"],
)