cc_library(
    name = "common",
    hdrs = glob(["common/*.h"]),
    srcs = glob(["common/*.c"]),
    include_prefix = "chip_hal",
    strip_include_prefix = "common",
    alwayslink=True,
    visibility = ["//visibility:public"],
)
