cc_library(
    name = "lib",
    srcs = [
        "st7920.c",
        "spi_sw.c",
        "spi_sw.h",
        "st7920.h",
    ],
    hdrs = [
        "spi_sw.h",
        "st7920.h",
    ],
    deps = [
        "//lib/common:lib",
        "//lib/hal/common:lib",
        "//spool/platforms/common:lib",
    ],
    visibility = ["//visibility:public"],
)