cc_library(
    name = "lib",
    srcs = [
        "st7920.c",
    ],
    hdrs = [
        "st7920.h",
    ],
    include_prefix = "drivers",
    deps = [
        "//lib/common:lib",
        "//lib/hal/common:lib",
        # "//spool/platform:runtime",
    ],
    visibility = ["//visibility:public"],
)