#pragma once

#define MOTION_AXIS 3

enum Axis {
    X_AXIS = 0,
    Y_AXIS,
    Z_AXIS,
    E_AXIS,
    NR_AXIS,
};

enum Stepper {
    STEPPER_A = 0,
    STEPPER_B,
    STEPPER_C,
    STEPPER_D,
    NR_STEPPER,
};

#define PLATFORM_MOTION_LIMIT_X_AXIS 185
#define PLATFORM_MOTION_LIMIT_Y_AXIS 180
#define PLATFORM_MOTION_LIMIT_Z_AXIS 120

#define PLATFORM_MOTION_STEPS_PER_MM_STEPPER_A 80
#define PLATFORM_MOTION_STEPS_PER_MM_STEPPER_B 80
#define PLATFORM_MOTION_STEPS_PER_MM_STEPPER_C 400
#define PLATFORM_MOTION_STEPS_PER_MM_STEPPER_D 800

#define PLATFORM_MOTION_STEPS_PER_MM_X_AXIS 80
#define PLATFORM_MOTION_STEPS_PER_MM_Y_AXIS 80
#define PLATFORM_MOTION_STEPS_PER_MM_Z_AXIS 400
#define PLATFORM_MOTION_STEPS_PER_MM_E_AXIS 800
