cc_library(
    name = "lib",
    srcs = [
        "encoder.h",
        "encoder.c",
    ],
    hdrs = [
        "encoder.h",
    ],
    deps = [
        "//lib/common:lib",
        "//lib/hal/common:lib",
	"//spool/platforms/common:lib",
    ],
    visibility = ["//visibility:public"],
)
