
cc_library(
    name="lib",
    srcs=[
        "ui.h",
        "ui.c",
    ],
    hdrs=["ui.h"],
    deps=[
        "//lib/lvgl:lib",
        "//lib/freertos",
    ],
    visibility=["//visibility:public"],
)