cc_library(
    name = "lib",
    srcs = [
        "bltouch.h",
        "bltouch.c",
    ],
    hdrs = [
        "bltouch.h",
    ],
    deps = [
        "//lib/common:lib",
        "//lib/hal/common:lib",
	    "//spool/platforms/common:lib",
    ],
    visibility = ["//visibility:public"],
)
